excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://FrOz3n-.github.io
title: Development Adventures
tagline: Software engineer by day, developer by night.
description: Hi there! I'm Ice Jovanoski, software developer @HASELT (www.haselt.com). Here you can read about some of the adventures I've had through the development process.
paginate: 5